# Generated by Django 4.2.7 on 2024-11-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hp', models.PositiveSmallIntegerField()),
                ('armor', models.PositiveSmallIntegerField()),
                ('attack', models.PositiveSmallIntegerField()),
                ('attack_delay', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
