# Generated by Django 4.2.7 on 2024-11-23 16:37

from django.db import migrations, models
import raid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField(null=True)),
                ('enemy_info', models.JSONField(default=raid.models.empty_list)),
                ('enemy_state_info', models.JSONField(default=raid.models.empty_list)),
                ('loot_info', models.JSONField(default=raid.models.empty_list)),
                ('loot_state_info', models.JSONField(default=raid.models.empty_list)),
                ('image', models.ImageField(upload_to='static')),
            ],
        ),
    ]
