# Generated by Django 4.2.7 on 2024-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='armor',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='attack_delay',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='damage',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot',
            field=models.CharField(choices=[('head', 'head'), ('chest', 'chest'), ('arms', 'arms'), ('legs', 'legs'), ('feet', 'feet'), ('rhand', 'right hand'), ('lhand', 'left hand'), ('backpack', 'backpack')], max_length=64, null=True),
        ),
    ]
