# Generated by Django 4.2.7 on 2024-11-23 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'heroes',
            },
        ),
        migrations.CreateModel(
            name='HeroInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hero.hero')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hero.hero')),
            ],
        ),
        migrations.CreateModel(
            name='StorageRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hero.storage')),
            ],
        ),
        migrations.CreateModel(
            name='HeroInventoryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hero.heroinventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='HeroEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('head', 'head'), ('chest', 'chest'), ('arms', 'arms'), ('legs', 'legs'), ('feet', 'feet'), ('rhand', 'right hand'), ('lhand', 'left hand'), ('backpack', 'backpack')], max_length=64)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hero.hero')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item')),
            ],
        ),
    ]
