# Generated by Django 4.2.7 on 2023-11-08 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_hero_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='inventory',
        ),
        migrations.AddField(
            model_name='storage',
            name='hero',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hero.hero'),
        ),
    ]
