# Generated by Django 4.2.7 on 2024-10-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_armor_item_attack_delay_item_damage_and_more'),
        ('hero', '0002_alter_hero_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hero.hero')),
            ],
        ),
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='HeroEquipment',
        ),
        migrations.CreateModel(
            name='HeroInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hero.heroinventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item')),
            ],
        ),
    ]
