# Generated by Django 4.2.7 on 2023-11-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('hero', '0003_remove_hero_inventory_storage_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='count',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='item',
        ),
        migrations.CreateModel(
            name='StorageRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hero.storage')),
            ],
        ),
    ]
