# Generated by Django 4.2.7 on 2024-10-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_heroinventory_rename_inventoryitem_heroequipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinventoryitem',
            name='count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='storagerow',
            name='count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
