# Generated by Django 4.2.7 on 2023-11-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_remove_storage_count_remove_storage_item_storagerow'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='name',
            field=models.CharField(default='asds', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
