# Generated by Django 4.2.7 on 2024-11-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_armor_item_attack_delay_item_damage_and_more'),
        ('hero', '0004_alter_heroinventoryitem_count_alter_storagerow_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroInventoryItem',
            new_name='HeroInventoryRow',
        ),
    ]
