# Generated by Django 4.2.7 on 2023-11-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_hero_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'heroes'},
        ),
        migrations.AlterField(
            model_name='storage',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hero.hero'),
        ),
    ]
